STY-7: Toast component
allbin/styles pull request #8
Opened 2024-06-05 14:52 UTC by NoahHakansson

2024-06-10 09:05 UTC, FritjofCavallin requested changes

2024-06-10 09:05 UTC, FritjofCavallin commented on src/components/Toast/useToast.tsx
> +  t(<ToastMsg {...props} icon={props.icon ? props.icon : icons.default} />, {
Borde räcka med ´props.icon ?? icons.default´.
Även motsvarande på kommande rader

2024-06-10 09:25 UTC, NoahHakansson commented on src/components/Toast/Toast.tsx
> +*/
Detta är en liten "guide" tänkte jag så man inte missar att importera CSS filen osv. Men skulle kanske kunna vara Lite tydligare att det är en guide på något sätt.

2024-06-13 08:08 UTC, FritjofCavallin requested changes
* Add hover effect to close-button
* Don't use pointer cursor if toast is not clickable

2024-06-13 08:08 UTC, FritjofCavallin commented on src/components/Toast/GalleryToast.tsx
> +        Error toast (autoClose time 500ms)
Feels wrong to say that the close time is 500ms but in reality error toasts never close automatically

2024-06-13 08:28 UTC, FritjofCavallin approved these changes

2024-06-13 08:28 UTC, merged